FROM ubuntu:latest

LABEL maintianer="venkat05091990@gmail.com"
LABEL version="0.1"
LABEL description="This is custom docker image created for data preprocessing, includes python pandas numpy papermill jupyterlab"

RUN apt-get update \
	&& apt-get upgrade 

RUN	apt-get install sudo 

RUN sudo apt-get install -y wget \
	&& sudo mkdir ./usr/app \
	&& mkdir ./usr/app/data_preprocessing

RUN sudo apt update
RUN sudo apt install -y software-properties-common
RUN sudo add-apt-repository -y ppa:deadsnakes/ppa 

ENV TZ=Asia/Kolkata
RUN sudo apt install -y python3.9
RUN sudo apt install -y python3-pip
RUN sudo pip3 install --no-cache-dir --upgrade pip

WORKDIR /usr/app/data_preprocessing
COPY requirements.txt requirements.txt
RUN sudo pip3 install --no-cache-dir -r requirements.txt

COPY data data
COPY notebooks notebooks
COPY run_preprocessing_batch.py run_preprocessing_batch.py